### ISSUE TITLE
ncWMS access points

### ISSUE THREAD

**Issue by eriktks** [ReGIS-org/server#1]
We still need to find out how to access stuff in ncWMS from outside. For this we probably need WMS (Web Map Services). Useful links:

* https://reading-escience-centre.gitbooks.io/ncwms-user-guide/content/04-usage.html
* http://portal.opengeospatial.org/files/?artifact_id=14416 (pdf: pages: 77/78)
* http://portal.opengeospatial.org/files/?artifact_id=30912 (pdf: pages 14-17)

**Comment by bakhshir** [comment]
I found these useful but did not try them out:
http://www.onegeology.org/howto/1_4.html
https://server.arcgis.com/en/server/10.3/publish-services/windows/wms-services.htm

**Comment by dafnevk** [comment]
The WMS acesspoint is: `<adress>/wms`.

An example request for our docker image, with dataset called `dataset1` : 

 `http://localhost/ncWMS/wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.1&DATASET=dataset1`
